# The deployment container image
FROM docker.io/oraclelinux:9-slim

# Pass in the JAR file as an argument to the container image build
ARG APP_FILE

EXPOSE 8080

# Copy the native executable into the container
COPY ${APP_FILE}  /app
ENTRYPOINT ["/app"]