# The deployment Image
FROM docker.io/oraclelinux:8-slim

# Pass in the JAR file as an argument to the image build
ARG APP_FILE

EXPOSE 8080

# Copy the native executable into the containers
COPY ${APP_FILE}  /app
ENTRYPOINT ["/app"]