FROM container-registry.oracle.com/graalvm/jdk:25 AS build
COPY . /webserver
WORKDIR /webserver
RUN ./mvnw --no-transfer-progress clean package

# Distoless Java 25 (Debian)
FROM eclipse-temurin:25
COPY --from=build /webserver/target/webserver-0.1.jar webserver-0.1.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "webserver-0.1.jar"]