FROM container-registry.oracle.com/graalvm/native-image:24 AS nativebuild
COPY . /webserver
WORKDIR /webserver
# Build a dynamically linked native image with default configuration
RUN ./mvnw -Dmaven.test.skip=true -Pnative native:compile

# Distroless Java Base - provides glibc and other libraries needed by the JDK
FROM gcr.io/distroless/java-base-debian12
COPY --from=nativebuild /webserver/target/webserver.dynamic /
EXPOSE 8000
ENTRYPOINT ["/webserver.dynamic", "-b", "0.0.0.0", "-d", "/web"]