FROM container-registry.oracle.com/graalvm/jdk:23 AS build
COPY . /webserver
WORKDIR /webserver
RUN ./mvnw clean package

FROM gcr.io/distroless/java21-debian12
COPY --from=build /webserver/target/webserver-0.0.1-SNAPSHOT.jar webserver-0.0.1-SNAPSHOT.jar  
EXPOSE 8080  
ENTRYPOINT ["java", "-jar", "webserver-0.0.1-SNAPSHOT.jar"]